-- 行末の空白をまとめて削除(カーソル位置は維持)
vim.api.nvim_create_user_command("StripWhitespaces", function()
  local curpos = vim.api.nvim_win_get_cursor(0)
  vim.cmd([[keeppatterns %s/\s\+$//e]])
  vim.api.nvim_win_set_cursor(0, curpos)
end, { desc = "Strip trailing whitespaces" })
