#-----------------------------------------------------------------------------------
# For Neovim and Vim
[[plugins]] # Emmet
repo = 'mattn/emmet-vim'
on_ft = ['html']
if = '!exists("g:vscode")'
hook_add = '''
  let g:user_emmet_leader_key = '<M-e>'
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = 'NERDTreeToggle'
if = '!exists("g:vscode")'
hook_add = '''
  nnoremap <M-f> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'dense-analysis/ale'
on_ft = ['nim']
if = '!exists("g:vscode")'
hook_add = '''
  source ~/.vim/plughook/ale-hook.vim
'''

#-----------------------------------------------------------------------------------
# For only Neovim
[[plugins]]
repo = 'neoclide/coc.nvim'
if = 'has("nvim") && !exists("g:vscode")'
rev = 'release'
on_i = 1
merged = '0'
hook_source = '''
  source ~/.vim/plughook/coc-hook.vim
  let b:coc_pairs_disabled = ['<']
'''
