# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  - trigger: ";espanso"
    replace: "Hi there!"

  - trigger: ";a "
    replace: "ありがとうございます！"

  - trigger: ";v "
    replace: "--version "

  - trigger: ";vv "
    replace: "--verbose "

  - trigger: ";h "
    replace: "--help "

  - trigger: ";year "
    replace: "{{year}}"
    vars:
      - name: year
        type: date
        params:
          format: "%Y"

  - trigger: ";now "
    replace: "{{now}}"
    vars:
      - name: now
        type: date
        params:
          format: "%H:%M:%S"

  - trigger: ";m "
    replace: "{{month}}"
    vars:
      - name: month
        type: date
        params:
          format: "%Y-%m"

  - trigger: ";date "
    replace: "{{date}}"
    vars:
      - name: date
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: ";day "
    replace: "{{day}}"
    vars:
      - name: day
        type: date
        params:
          format: "(%a)"

  - trigger: ";sun "
    replace: "(日)"

  - trigger: ";mon "
    replace: "(月)"

  - trigger: ";tue "
    replace: "(火)"

  - trigger: ";wed "
    replace: "(水)"

  - trigger: ";thu "
    replace: "(木)"

  - trigger: ";fri "
    replace: "(金)"

  - trigger: ";sat "
    replace: "(土)"

  - trigger: ";weeks "
    replace: "月\n火\n水\n木\n金"

  - trigger: ";weeksl "
    replace: "- 月：\n- 火：\n- 水：\n- 木：\n- 金："

  - trigger: ":blush "
    replace: "😊"

  - trigger: ":bow "
    replace: "🙇"

  - trigger: ":cold "
    replace: "🥶"

  - trigger: ":exploding "
    replace: "🤯"

  - trigger: ":grin "
    replace: "😁"

  - trigger: ":hamster "
    replace: "🐹"

  - trigger: ":innocent "
    replace: "😇"

  - trigger: ":man_bow "
    replace: "🙇‍♂️"

  - trigger: ":man_bowing "
    replace: "🙇‍♂️"

  - trigger: ":melting "
    replace: "🫠"

  - trigger: ":muscle "
    replace: "💪"

  - trigger: ":partying "
    replace: "🥳"

  - trigger: ":play "
    replace: "🙏"

  - trigger: ":poo "
    replace: "💩"

  - trigger: ":rage "
    replace: "😡"

  - trigger: ":sob "
    replace: "😭"

  - trigger: ":sparkles "
    replace: "✨"

  - trigger: ":sweat "
    replace: "💦"

  - trigger: ":tada "
    replace: "🎉"

  - trigger: ":thinking "
    replace: "🤔"

  - trigger: ":thumbsup "
    replace: "👍"
