[theme]
name = "slick"
[theme.overrides]
# https://www.nerdfonts.com/cheat-sheet
# https://github.com/ryanoasis/powerline-extra-symbols
separator = "\ue0b2"


[icons]
name = "awesome"


[[block]]
block = "net"
format = "{ssid} {ip} {speed_down}"
interval = 5
use_bits = false
hide_missing = true
hide_inactive = true
[block.theme_overrides]
idle_bg = "#002b42"
idle_fg = "#93a1a1"


[[block]]
block = "cpu"
interval = 3
[block.theme_overrides]
idle_bg = "#00a0ff"
info_bg = "#dc9300"
warning_bg = "#fc620c"
critical_bg = "#ab2811"


[[block]]
block = "temperature"
collapsed = false
interval = 5
format = "{average}°"
chip = "*-isa-*"
[block.theme_overrides]
idle_bg = "#76e050"
idle_fg = "#333333"
info_bg = "#dc9300"
warning_bg = "#fc620c"
critical_bg = "#ab2811"


[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mug}GiB ({Mup}%)"
format_swap = "swap:{SUg}GiB ({SUp}%)"
[block.theme_overrides]
idle_bg = "#802fff"
warning_bg = "#fc620c"
critical_bg = "#ab2811"


[[block]]
block = "sound"
[block.theme_overrides]
idle_bg = "#ff86d3"
idle_fg = "#333333"


[[block]]
block = "battery"
device = "BAT1"
interval = 20
format = "{percentage}%"
allow_missing = true
hide_missing = true


[[block]]
block = "time"
interval = 5
format = "%m月%d日 %H:%M"
[block.theme_overrides]
idle_bg = "#6a3636"
